[package]
name = "codemp-proto"
description = "protocol definitions for codemp -- code multiplexer"
homepage = "https://code.mp"
repository = "https://github.com/hexedtech/codemp-proto"
authors = [
	"alemi <me@alemi.dev>",
	"zaaarf <me@zaaarf.foo>",
	"frelodev <frelodev@gmail.com>",
	"cschen <cschen@codemp.dev>"
]
license = "GPL-3.0-only"
version = "0.8.0"
edition = "2024"

[lib]
name = "codemp_proto"

[dependencies]
prost = "0.14"
tonic = { version = "0.14", default-features = false, features = ["codegen"] }
tonic-prost = "0.14"
serde = { version = "1.0", features = ["derive"], optional = true }
# glue (lua)
mlua = { version = "0.11", features = ["luajit", "serde"], optional = true }
mlua-serde-derive = { path = "../mlua-serde-derive/", optional = true }
# glue (js)
napi = { version = "3.1", features = ["napi10", "serde-json", "chrono_date"], optional = true } 
napi-derive = { version="3.1",  optional = true }
# glue (py)
pyo3 = { version = "0.28", features = ["multiple-pymethods", "uuid"], optional = true}
# glue (java)
jni = { version = "0.22", features = ["invocation"], optional = true }
jni-toolbox = { git = "https://github.com/hexedtech/jni-toolbox", rev = "c40e925510fd563763db5dec4df300615453054b", optional = true, features = ["uuid", "unsigned"] }

[build-dependencies]
tonic-prost-build = "0.14"

[features]
default = []
client = ["tonic/transport"]
server = ["tonic/transport"]
serde = ["dep:serde"]

lua = ["serde", "dep:mlua", "dep:mlua-serde-derive"]
js = ["dep:napi", "dep:napi-derive"]
py = ["dep:pyo3"]
java = ["dep:jni", "dep:jni-toolbox"]
