[package]
name = "codemp-proto"
version = "0.6.0"
edition = "2021"

[lib]
name = "codemp_proto"

[dependencies]
prost = "0.12.3"
tonic = "0.11.0"
uuid = "1.7.0"

[build-dependencies]
tonic-build = "0.11.0"
