syntax = "proto2";

package cursor;

import "common.proto";

// Handles cursor events and broadcasts them to all users.
service Cursor {
	// Retrieves all current cursor positions.
	rpc List(common.Empty) returns (CursorEventList);
	// Subscribe to a workspace's cursor events.
	rpc Attach (stream CursorUpdate) returns (stream CursorEvent);
	// Send the keep alive signal and renew the token.
	rpc KeepAlive (common.Empty) returns (common.Empty);
}

// A message representing a list of cursor events.
message CursorEventList {
	// A vector of cursor events.
	repeated CursorEvent cursors = 1;
}

// A message representing a position in a buffer.
message RowCol {
	// The row.
	required int32 row = 1;
	// The column.
	required int32 col = 2;
}

// A message representing a cursor position.
message CursorPosition {
	// The cursor's start position.
	required RowCol start = 1;
	// The cursor's end position.
	required RowCol finish = 2;
}

// A message representing an update to the cursor position.
message CursorUpdate {
	// The buffer where the cursor is located.
	required string buffer = 1;
	// A vector of cursor positions.
	repeated CursorPosition cursors = 2;
}

// A message representing a cursor event.
message CursorEvent {
	// The user moving the cursor.
	required string user = 1;
	// The new cursor position.
	required CursorUpdate position = 2;
}
