syntax = "proto2";

package files;

// A message representing a buffer path.
message BufferPath {
	// The path of a buffer.
	required string path = 1; 
}

// A message representing a node in the filetree.
message BufferNode {
	// The path of a buffer.
	required BufferPath path = 1;
	// Attributes of this buffer
	required BufferAttributes attributes = 2;
}

// Properties and modifiers of a buffer
message BufferAttributes {
	// Whether the buffer is auto-deleted once everyone has left it
	required bool ephemeral = 1;
}

// A message representing a filetree.
message BufferTree {
	// A vector of buffer nodes.
	repeated BufferNode buffers = 1;
}
