syntax = "proto2";

package session;

import "common.proto";

// Manages user workspaces and refreshes tokens.
service Session {
	// Attach to a session and receive events.
	rpc Attach (common.Empty) returns (stream SessionEvent);
	// Handle a workspace access request and return a workspace token for it given its UUID.
	rpc GetWorkspaceToken (WorkspaceIdentifier) returns (common.Token);
	// Quit a workspace given its UUID.
	rpc QuitWorkspace (WorkspaceIdentifier) returns (common.Empty);
	// Create a workspace.
	rpc CreateWorkspace (OwnedWorkspaceIdentifier) returns (common.Empty);
	// Delete a workspace given its UUID.
	rpc DeleteWorkspace (OwnedWorkspaceIdentifier) returns (common.Empty);
	// List all workspaces the user has been invited to.
	rpc FetchInvitedWorkspaces (common.Empty) returns (WorkspacesList);
	// List all workspaces the user owns.
	rpc FetchOwnedWorkspaces (common.Empty) returns (WorkspacesList);
	// Handle a workspace invite request.
	rpc InviteToWorkspace (InviteRequest) returns (common.Empty);
	// Accept a pending invite to a workspace given its UUID.
	rpc AcceptInvite (WorkspaceIdentifier) returns (common.Empty);
	// Reject a pending invite to a workspace given its UUID.
	rpc RejectInvite (WorkspaceIdentifier) returns (common.Empty);
	// Gets a user's full profile.
	rpc GetUserInfo (UserId) returns (common.UserInfo);
}

// A message representing a bare user id
message UserId {
	// The user unique id (their name)
	required string user = 1;
}

// A message identifying a specific owned workspace (meaning, owner is self)
message OwnedWorkspaceIdentifier {
	// The workspace's name.
	required string workspace = 1;
}

// A message identifying a specific workspace
message WorkspaceIdentifier {
	// The workspace's owner
	required string user = 1;
	// The workspace's name
	required string workspace = 2;
}

// A message representing a list of workspaces.
message WorkspacesList {
	// A vector of workspaces the user is invited to.
	repeated WorkspaceIdentifier workspaces = 1;
}

// A message representing an invitation to a workspace.
message InviteRequest {
	// The user the invitation is for.
	required string user = 1;
	// The workspace (by name) the invitation is for.
	required string workspace = 2;
}

/// Identifies different kinds of session events
enum SessionEventKind {
	// Event that occurs when you get invited to a workspace.
	InvitationEvent = 0;
	// Event that occurs when a user quits a workspace.
	QuitEvent = 1;
	// Event that occurs when an user accepts an invite to a workspace you are in.
	AcceptEvent = 2;
	// Event that occurs when an user rejects an invite.
	RejectEvent = 3;
}

// A message representing a session event.
message SessionEvent {
	/// The actual kind of session event
	required SessionEventKind kind = 1;
	// The user that created this event (sent invitation, rejected invite...)
	required string user = 2;
	// The workspace this event is related to
	required WorkspaceIdentifier workspace = 3;
}
