syntax = "proto2";

package session;

import "common.proto";

// Manages user workspaces and refreshes tokens.
service Session {

	rpc getEvents (common.Empty) returns (stream SessionEvent);
	// Handle a workspace access request and return a workspace token.
	rpc AccessWorkspace (WorkspaceRequest) returns (common.Token);
	// Create a workspace.
	rpc CreateWorkspace (OwnedWorkspaceRequest) returns (common.WorkspaceInfo);
	// Delete a workspace.
	rpc DeleteWorkspace (OwnedWorkspaceRequest) returns (common.Empty);
	// List all workspaces the user has been invited to.
	rpc FetchInvitedWorkspaces (common.Empty) returns (WorkspacesInvitedList);
	//List all workspaces the user owns.
	rpc FetchOwnedWorkspaces (common.Empty) returns (WorkspacesOwnedList);
	// Handle a workspace invite request.
	rpc InviteToWorkspace (InviteRequest) returns (common.Empty);
}

// A message representing a request for and owned workspace.
message OwnedWorkspaceRequest {
	// The workspace's name.
	required string name = 1;
}

// A message representing a request for a specific workspace.
message WorkspaceRequest {
	required common.Identifier id = 1;
}

// A message representing a list of workspaces.
message WorkspacesInvitedList {
	// A vector of workspaces the user is invited to.
	repeated common.WorkspaceInfo invited = 1;
}

// A message representing a list of workspaces.
message WorkspacesOwnedList {
	// A vector of workspaces owned by the user.
	repeated common.WorkspaceInfo owned = 1;
}

// A message representing an invitation to a workspace.
message InviteRequest {
	// The user the invitation is for.
	required string user = 1;
	// the workspace the invitation is for
	required common.Identifier workspace = 2;
}

// A message representing a session event.
message SessionEvent {
	// Event that occurs when you get invited to a workspace
	message InvitationEvent {
		// The user that invited you.
		required common.User user = 1;
	}
	// Event that occurs when a user leaves a workspace.
	message LeaveEvent {
		// The user that left.
		required common.User user = 1;
	}
	// Event that occurs when an user joins in a workspace you are in
	message JoinEvent {
		// The user that joined.
		required common.User user = 1;
	}
	oneof event {
		InvitationEvent invite = 1;
		LeaveEvent leave = 2;
		JoinEvent join = 3;
	}
}