syntax = "proto2";

package workspace;

import "common.proto";
import "files.proto";

// Handles workspace state management.
service Workspace {
	// Attach to a workspace.
	rpc Attach (common.Empty) returns (stream WorkspaceEvent);
	// Create a buffer within the workspace.
	rpc CreateBuffer (files.BufferNode) returns (common.Empty);
	// Handle a buffer access request and return a buffer token for it given its UUID.
	rpc GetBufferToken (files.BufferPath) returns (common.Token);
	// Transforms an ephemeral buffer in a persistent one given its UUID.
	rpc PinBuffer (files.BufferPath) returns (common.Empty);
	// Transforms a persistent buffer in an ephemeral one given its UUID.
	rpc UnPinBuffer (files.BufferPath) returns (common.Empty);
	// Delete a buffer given its UUID.
	rpc DeleteBuffer (files.BufferPath) returns (common.Empty);
	// Retrieves the buffers in the workspace.
	rpc FetchBuffers (common.Empty) returns (files.BufferTree); 
	// Retrieves the users in the workspace.
	rpc FetchUsers (common.Empty) returns (UserList);
	// Retrives the users within a given buffer.
	rpc FetchBufferUsers (files.BufferPath) returns (UserList);
	// Send the keep alive signal and renew the token.
	rpc KeepAlive (common.Empty) returns (common.Empty);
}

// A message representing a list of users.
message UserList {
	// A vector of users.
	repeated string users = 1;
}

// Identifies different kind of workspace events
enum WorkspaceEventKind {
	// Event that occurs when a user joins a workspace.
	UserJoinWorkspace = 0;
	// Event that occurs when a user leaves a workspace.
	UserLeaveWorkspace = 1;
	// Event that occurs when a file is created in a workspace.
	FileCreate = 2;
	// Event that occurs when a file is renamed in a workspace.
	FileRename = 3;
	// Event that occurs when a file is deleted in a workspace.
	FileDelete = 4;
	// Event that occurs when a user joins a buffer.
	UserJoinBuffer = 5;
	// Event that occurs when a user leaves a buffer.
	UserLeaveBuffer = 6;
}

// A message representing a workspace event.
message WorkspaceEvent {
	// The event type
	required WorkspaceEventKind kind = 1;
	// The user that joined/left (possibly a buffer)
	optional string user = 2;
	// Path to relevant buffer (deleted/created/left by user...)
	optional string path = 3;
	/// Whether relevant buffer is ephemeral
	optional bool ephemeral = 4;
	// If this is a FileRename, new path will be here
	optional string after = 5;
}
