syntax = "proto2";

package workspace;

import "common.proto";
import "buffer.proto";

// Handles workspace state management.
service Workspace {
	// Attach to a workspace.
	rpc Attach (common.Empty) returns (stream WorkspaceEvent);
	// Create a buffer within the workspace.
	rpc CreateBuffer (buffer.BufferNode) returns (common.Empty);
	// Handle a buffer access request and return a buffer token for it given its UUID.
	rpc GetBufferToken (buffer.BufferPath) returns (common.Token);
	// Transforms an ephemeral buffer in a persistent one given its UUID.
	rpc PinBuffer (buffer.BufferPath) returns (common.Empty);
	// Transforms a persistent buffer in an ephemeral one given its UUID.
	rpc UnPinBuffer (buffer.BufferPath) returns (common.Empty);
	// Delete a buffer given its UUID.
	rpc DeleteBuffer (buffer.BufferPath) returns (common.Empty);
	// Retrieves the buffers in the workspace.
	rpc FetchBuffers (common.Empty) returns (buffer.BufferTree); 
	// Retrieves the users in the workspace.
	rpc FetchUsers (common.Empty) returns (UserList);
	// Retrives the users within a given buffer.
	rpc FetchBufferUsers (buffer.BufferPath) returns (UserList);
	// Send the keep alive signal and renew the token.
	rpc KeepAlive (common.Empty) returns (common.Empty);
}

// A message representing a list of users.
message UserList {
	// A vector of users.
	repeated string users = 1;
}

// Identifies different kind of workspace events.
enum WorkspaceEventKind {
	// Event that occurs when a user joins a workspace.
	UserJoinWorkspace = 1;
	// Event that occurs when a user leaves a workspace.
	UserLeaveWorkspace = 2;
	// Event that occurs when a user joins a buffer.
	UserJoinBuffer = 3;
	// Event that occurs when a user leaves a buffer.
	UserLeaveBuffer = 4;
	// Event that occurs when a buffer is created in a workspace.
	BufferCreate = 5;
	// Event that occurs when a buffer is renamed in a workspace.
	BufferRename = 6;
	// Event that occurs when a buffer is deleted in a workspace.
	BufferDelete = 7;
	// Event fired when a buffer has its attributes changed.
	BufferAttrsUpdated = 8;
}

// A message representing a workspace event.
message WorkspaceEvent {
	// The event type.
	required WorkspaceEventKind kind = 1;
	// The user that caused this event.
	optional string user = 2;
	// Path to buffer affected by this event.
	optional string path = 3;
	// If this is a BufferCreate or BufferAttrsUpdated, the new buffer attributes.
	optional buffer.BufferAttributes attributes = 4;
	// If this is a BufferRename, new path will be here.
	optional string after = 5;
}
