name: build+test

on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Cargo Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        #  - beta
        #  - nightly
        # TODO should re-enable future toolchains so we get warnings on breaking changes
    steps:
      - uses: arduino/setup-protoc@v2
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --features=${{ matrix.features }}
      - run: cargo test --verbose --features=${{ matrix.features }}
